### PR TITLE
Update stipend-us.csv for Northwestern University

### PR DESCRIPTION
**Pull request by wangxiao1254**
- **Institution name(s)**: 
Northwestern University

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: 
- Own data point, also at https://nugradworkers.org/full-tentative-agreement-bc-recommendation/. 45000 stipend will start 2024 fall

- **Link to the [MIT Living Wage Calculator](http://livingwage.mit.edu/)**: 
  
  > Note: Please use The number in `Typical Expenses -> Required annual income before taxes -> 1 Adult & 0 Children` as the annual local living wage.

- **Additional Comments (Optional)**:

### CODE REVIEW

**Comment by mjc0608** [comment]
You can add the verified checkmark. Please change the two "No" into "Yes https://nugradworkers.org/full-tentative-agreement-bc-recommendation/"

**Comment by mjc0608** [comment]
I merged this. However, if you can find some official source of the stipend increase, I can add a checkmark. The link you sent was a proposal from the union and it's not official.

**Comment by wangxiao1254** [comment]
Thank you! I will follow up with a link once it appears on the NU official website.

**Comment by wangxiao1254** [comment]
I hope https://www.northwestern.edu/graduate-student-unionization/union-contract/ is sufficient. See "Compensation Highlights".

**Comment by wangxiao1254** [comment]
@mjc0608 It has been updated at https://www.tgs.northwestern.edu/funding/

**Comment by mjc0608** [comment]
Sorry, didn't see the message. It's updated now

**Pull request merged**
