### PR TITLE
Update and highlight disclaimer

### PR DESCRIPTION
**Pull request by jiong-zhu**
Add disclaimer note in the information box (see preview below), and add explicit legal disclaimer from [BSD](https://opensource.org/license/bsd-3-clause/). 
image

### CODE REVIEW

**Comment by TonyZhangND** [comment]
Should the BSD clause be in some text file in the repo, rather than on the site?

**Comment by mjc0608** [comment]
Actually, we are actually not BSD :)

**Comment by mjc0608** [comment]
Or I'm confused with license and copyright :(

**Comment by jiong-zhu** [comment]
Yeah I know we are actually not BSD, but I just borrowed their disclaimer. I didn't find that in our current license.

**Pull request merged**
