### PR TITLE
Make formatting of university campus names consistent

### PR DESCRIPTION
**Pull request by noah-curran**
Many large state universities have multiple campuses. When absent, I added this in. There are a few ways this information was incorporated. E.g., `The University of Texas at Austin`, `University of Michigan, Ann Arbor`. I've made all in the `<university>, <campus>` format.

### CODE REVIEW

**Comment by TonyZhangND** [comment]
I agree that we should be consistent, and there is definitely inconsistent uses of "," vs. "-:". However, the use of "at" is sometimes because that is actually the official name.

For instance, UT Austin is officially "The University of Texas at Austin". This is also reflected in CSRankings.

**Comment by noah-curran** [comment]
> For instance, UT Austin is officially "The University of Texas at Austin". This is also reflected in CSRankings.

Good to know. Then let's try to shift everything to be consistent with the CS rankings names for institutions. I'll update the PR with this knowledge.

**Comment by noah-curran** [comment]
Something I am noticing is that CS rankings is not always consistent. E.g, `University of Michigan` (should be Ann Arbor) vs. `University of Michigan-Dearborn` (does not have space around "-" like other institutions), or `Ohio State University` (normally includes "The") vs. `The University of Alabama`. Should we incorporate a styling standard since CS rankings seems to have a loose standard?

**Comment by mjc0608** [comment]
I think we should use whatever CSRankings uses, just to make the website more satirical.

**Comment by TonyZhangND** [comment]
Personally I've been loosely using university websites for ground truth on what they call themselves. I think it's better we use proper official naming, rather than following CS Rankings. It makes us better than CS Rankings haha

**Comment by noah-curran** [comment]
@TonyZhangND Generally, I agree with you, but sometimes the name that main campuses call themselves is not accurate and could lead to confusion. For instance, ["University of Michigan" officially refers to itself dropping "Ann Arbor"](https://umich.edu/). But there is a [CS PhD program at "University of Michigan - Dearborn"](https://umdearborn.edu/cecs/departments/computer-and-information-science/graduate-programs/phd-computer-and-information-science). Also, [Pennsylvania State University officially refers to itself as Penn State](https://www.psu.edu/) or [Massachusetts Institute of Technology refers to itself at MIT](https://www.mit.edu/). I think setting a standard would probably be best since even the ground truth isn't always consistent.

I propose the following:
- Start with using official name at it would appear on the diploma. (E.g., `MIT` ==> `Massachusetts Institute of Technology`)
- Shorten `University` to `Univ.` (E.g., `University of Virginia` ==> `Univ. of Virginia`)
- If a university (or university system) has multiple campuses, refer to campus location using either `at` or ` - `, whichever is official. If no official usage, default to ` - `. (E.g., `Univ. of Illinois at Chicago` or `Univ. of Michigan - Ann Arbor` or `Purdue Univ. - West Lafayette)
- Drop "The" if it appears at the start of the name. (E.g., `The Ohio State Univ. - Columbus` ==> `Ohio State Univ. - Columbus`)
- Special case: for the SUNY or CUNY system, use it after the ` - `. (E.g., `Stony Brook Univ.` ==> `Stony Brook Univ. - SUNY` or `Univ. at Buffalo` ==> `Univ. at Buffalo - SUNY`)

**Comment by TonyZhangND** [comment]
I like this system. Two points
1. I don't know how I feel about univ vs university. We can leave it as University first in the CSV, and then in a separate commit change the front end to display univ over university?
2. In the case of OSU, I didn't know it has multiple campuses, and I can't find info indicating as such?

**Comment by noah-curran** [comment]
@TonyZhangND Sure, fair enough on the university point. I think my concern is that some names can get long. We could have an adaptive UI that shorted University when it senses the line is getting to be too many characters.

[Here is a source for OSU regional campuses.](http://undergrad.osu.edu/regional-campuses)

**Comment by TonyZhangND** [comment]
Perfect!

**Comment by TonyZhangND** [comment]
Could you also describe this convention in the readme? Thanks!

**Comment by noah-curran** [comment]
I think this snuck into the final during the merge conflict resolution:
- `"The University of Texas at Dallas",23400,25800,36973,50, public` ("The" appeared)

**Comment by TonyZhangND** [comment]
Fixed. Thanks!

**Pull request merged**
