### PR TITLE
Added fee info for UMass Amherst, plus offer letter for the coveted blue check :)

### PR DESCRIPTION
**Pull request by emeryberger**
- **Institution name(s)**: 

UMass Amherst

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: 

Offer letter (see attached).

[UMass Admissions Letter.pdf](https://github.com/CSStipendRankings/CSStipendRankings/files/11425826/UMass.Admissions.Letter.pdf)

### CODE REVIEW

**Comment by jiong-zhu** [comment]
Thank you Prof. Berger! 

I noticed that the offer letter includes a 95% Health Insurance Waiver, thus the out-of-pocket insurance premium is 3840 * 0.05 = $192 / year for an individual student. Currently we do include out-of-pocket premium in the fees column as well, so I believe the total fees per year should be $1322.25. We will update the fees and added the blue check mark!

**Comment by jiong-zhu** [comment]
@mjc0608 @TonyZhangND How do we currently handle 8-month or 9-month guaranteed funding? I see that UMass does not guarantee summer funding for year 2-5, and 27428.4 / 37533.6 = 73.1%.

**Comment by TonyZhangND** [comment]
Based on some offline discussion, we need to formalize our definition of our SUMMER funding label.

* If 99/100 students get summer funding, do we say there is summer funding?
* If everyone gets summer funding but it is not in the contract, do we say there is summer funding?

At this point, I think we are tending towards NO. 

## Side note though
Summer funding guarantees are difficult to crowd source. I for one didn't know our summer funding wasn't guaranteed until yesterday. Perhaps we can have distinct SUMMER-AVAILABLE and SUMMER-GUARANTEED labels.
SUMMER-AVAILABLE gets upgraded to SUMMER-GUARANTEED when there is contractual proof. 


Anyhow, we can discuss this as a separate issue, and close this PR for now

**Comment by jiong-zhu** [comment]
Updates to fees and verification status are made in https://github.com/CSStipendRankings/CSStipendRankings/commit/82fcc3b0149713b1efe7e896a82ab43a2d3af933, so I am closing this PR. Thank you again for your contribution!

**Comment by noah-curran** [comment]
> I for one didn't know our summer funding wasn't guaranteed until yesterday.

@TonyZhangND Apparently UMich CSE now guarantees it, meaning they incorporate it as part of their offer-letters. This is recent as of this admissions cycle. Something we should consider is whether we want to consider *institutional* guarantee or *department* guarantee. It seems you are referring to institutional guarantees, which you're right that UMich doesn't. My point here is that if the summer funding is guaranteed as part of the department offer letter, then perhaps that is good enough for this ranking?

**Comment by TonyZhangND** [comment]
I see! Department guarantee is definitely sufficient 👍

**Comment by noah-curran** [comment]
> Can we get an offer letter to verify this?

Would also like to see it verified because what I have heard is just from faculty word of mouth. I can see if an incoming PhD student is willing to share.

**Pull request closed without merging**
