### PR TITLE
wage relative to living

### PR DESCRIPTION
**Pull request by joydddd**
- **Institution name(s)**: 

- **Source of the stipend and fee data (e.g., your own data point, a link to an official website, etc.)**: 

- **Link to the [MIT Living Wage Calculator](http://livingwage.mit.edu/)**: 
  
  > Note: Please use The number in `Typical Expenses -> Required annual income before taxes -> 1 Adult & 0 Children` as the annual local living wage.

- **Additional Comments (Optional)**:  Add relative wages

- **Notify**: @mjc0608 @jiong-zhu @pyjhzwh @eltsai

### CODE REVIEW

**Comment by mjc0608** [comment]
A minor issue is "Related to Living" should not use "$".

Also, this ranking seems pretty similar to "After Fees and Living", do we need both? What are your opinions @pyjhzwh @TonyZhangND @jiong-zhu @shibo-chen

**Comment by TonyZhangND** [comment]
@mjc0608 As per our previous discussion, I agree with you that the ratio isn't too relevant.

@joydddd what are your thoughts?

**Comment by joydddd** [comment]
I can make this an optional tab: chose between display absolute value & relative values.

**Comment by TonyZhangND** [comment]
On second thought, I kinda like the relative values.
@mjc0608 Should it be a new column or a toggle between absolute and relative value? What do you think?

**Comment by mjc0608** [comment]
I guess a toggle would be better. We can put a "<select>" there

**Comment by jiong-zhu** [comment]
I feel showing both the display absolute values and the relative values by default is a bit too much for me. A select or toggle would be ideal.

**Comment by mjc0608** [comment]
I'm closing this pull request because no one is working on the toggle. We can open it again if someone volunteers.

**Pull request closed without merging**
